version: "3.9"

services:
  backend:
    container_name: nest-backend
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "file:./dev.db"
    command: sh -c "rm -f ./prisma/dev.db && pnpm install && pnpm prisma migrate dev && pnpm start:dev"

    networks:
      - app-network

  frontend:
    container_name: next-frontend
    build:
      context: ./frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:5000"
    command: sh -c "npm install && npm run dev"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
